# Lab 5 - Classification :  k-NN and Naive Bayes (using sklearn libraries)

## k-NN

Use **"Pima Indians Diabetes Dataset from UCI Machine Learning Repository"** for this question.It is a binary class dataset. Split the dataset into train(80%), validation(10%) and test sets(10%).

Run k-Nearest neighbours for different k values. Choose your own subset of k (atleast 10) and choose the best value of k from this subset. In solving real-world problems, the values of k are chosen based on experience and hence it is a tunable hyperparameter. Select the k, using validation set, which returns the best accuracy score. Report accuracy score by performing k-NN on the test dataset using the chosen k value. 

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

In [12]:
df = pd.read_csv('diabetes.csv')
X = df
y = df['Outcome']
del X['Outcome']
X_train, Xdash, y_train, ydash = train_test_split(X, y, train_size=0.8, random_state=0)
X_val, X_test, y_val, y_test = train_test_split(Xdash, ydash, train_size=0.5, random_state=0)

k = [1,3,7,11,13,15,17,19,21,23,25,27,29,33,47,57]
error = []
for i in range(len(k)):
    classifier = KNeighborsClassifier(n_neighbors=k[i])
    classifier.fit(X_train, y_train)
    y_pred = classifier.predict(X_val)
    error.append(np.mean(y_pred != y_val))
    
for i in range(len(k)):
    print('Value of k: %f, Accuracy on Validation set: %f' %(k[i], 1- error[i]))

Value of k: 1.000000, Accuracy on Validation set: 0.675325
Value of k: 3.000000, Accuracy on Validation set: 0.753247
Value of k: 7.000000, Accuracy on Validation set: 0.831169
Value of k: 11.000000, Accuracy on Validation set: 0.818182
Value of k: 13.000000, Accuracy on Validation set: 0.831169
Value of k: 15.000000, Accuracy on Validation set: 0.818182
Value of k: 17.000000, Accuracy on Validation set: 0.818182
Value of k: 19.000000, Accuracy on Validation set: 0.818182
Value of k: 21.000000, Accuracy on Validation set: 0.831169
Value of k: 23.000000, Accuracy on Validation set: 0.831169
Value of k: 25.000000, Accuracy on Validation set: 0.818182
Value of k: 27.000000, Accuracy on Validation set: 0.818182
Value of k: 29.000000, Accuracy on Validation set: 0.818182
Value of k: 33.000000, Accuracy on Validation set: 0.844156
Value of k: 47.000000, Accuracy on Validation set: 0.805195
Value of k: 57.000000, Accuracy on Validation set: 0.818182


C:\Users\User\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2069: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [13]:
classifier = KNeighborsClassifier(n_neighbors=33)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
error = (np.mean(y_pred != y_test))
print('Accuracy on test set for k = 33: ', 1-error)

Accuracy on test set for k = 33:  0.7532467532467533


Accuracy on test set for k = 33:  0.7532467532467533


## Naive Bayes

Use **"Optical recognition of handwritten digits dataset"** for this question. ** Download dataset from sklearn**. The dataset has 10 classes and 64 attributes (8x8 images). Visualise images from the dataset. Perform a train test split in the ratio 4:1. 

Naive Bayes - perform multiclass classification to classify the dataset into one of the ten classes. Experiment with the priors (Gaussian and Bernoulli) and report the best prior. Report the accuracies in terms of F1 scores and the confusion matrix (use sklearn functions for this too).



In [15]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.datasets import load_digits

In [16]:
digits = load_digits()
X, y = digits.data, digits.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

In [19]:
b_clf = BernoulliNB()
g_clf = GaussianNB()
y_pred_ber = b_clf.fit(X_train, y_train).predict(X_test)
print("F1 score for BernoulliNB classifier", (f1_score(y_test, y_pred_ber, average='weighted')))

y_pred_gauss = g_clf.fit(X_train, y_train).predict(X_test)
print("F1 score for GaussianNB classifier", (f1_score(y_test, y_pred_gauss, average='weighted')))

F1 score for BernoulliNB classifier 0.827099717314215
F1 score for GaussianNB classifier 0.8529545573049961


In [22]:
print("Confusion Matrix for GaussianNB classifier \n", confusion_matrix(y_test, y_pred_gauss))
print("\n")
print("Confusion Matrix for BernoulliNB classifier \n", confusion_matrix(y_test, y_pred_ber))

Confusion Matrix for GaussianNB classifier 
 [[30  0  0  0  0  0  0  0  0  0]
 [ 0 34  1  0  0  0  1  1  6  4]
 [ 0  3 29  1  1  0  0  0  4  0]
 [ 0  1  1 24  0  0  0  4  3  1]
 [ 0  0  0  0 33  1  0  4  0  0]
 [ 0  0  0  0  0 27  0  1  0  0]
 [ 0  0  0  0  0  0 34  0  0  0]
 [ 0  0  0  0  0  0  0 34  0  1]
 [ 0  2  0  0  0  1  0  0 33  0]
 [ 0  0  0  0  0  2  1  4  4 29]]


Confusion Matrix for BernoulliNB classifier 
 [[30  0  0  0  0  0  0  0  0  0]
 [ 0 28  5  0  1  1  0  0  8  4]
 [ 0  1 31  3  0  0  0  0  3  0]
 [ 0  0  0 28  0  1  0  1  2  2]
 [ 0  0  0  0 35  0  0  3  0  0]
 [ 0  0  0  0  1 22  0  0  0  5]
 [ 0  0  0  0  0  0 34  0  0  0]
 [ 0  0  0  0  1  1  0 33  0  0]
 [ 0  1  0  1  0  0  0  0 29  5]
 [ 0  1  0  1  2  1  0  4  3 28]]


Gaussian prior gave better results than Bernoulli prior